config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#home'
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :products
  resources :orders

  post '/guest_login', to: 'static_pages#guest_login'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy

  def total_price
    order_details.sum(&:sub_tatal)
  end

  def order_status
    if order_details.any? {|order_detail| order_detail.shipment_status.shipment_status_name == "準備中"}
      "準備中"
    else
      "発送中"
    end
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :shipment_status
  belongs_to :product

  def sub_tatal
    product.price * order_quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :product_status
  belongs_to :sale_status
  belongs_to :category
  has_many :purchases, dependent: :destroy
  def self.search(search, category_id)
    products = Product.all
    products = products.where(["product_name LIKE ?", "%#{search}%"]) if search.present?
    products = products.where(["category_id = ?", category_id]) if category_id.present?
    products
  end
end

app/models/product_status.rb
class ProductStatus < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :product
end

app/models/sale_status.rb
class SaleStatus < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/shipment_status.rb
class ShipmentStatus < ApplicationRecord
  has_many :order_details, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  with_options presence: true do
    validates :password, format: { with: /\A[a-zA-Z0-9]+\z/ }, length: { in: 6..15 }
    validates :last_name, length: { maximum: 10 }
    validates :first_name, length: { maximum: 10 }
    validates :zipcode, format: { with: /\A\d{3}\d{4}\z/ }, length: { maximum: 8 }
    validates :prefecture, length: { maximum: 5 }
    validates :municipality, length: { maximum: 10 }
    validates :address, length: { maximum: 15 }
    validates :apartments, length: { maximum: 20 }
    validates :email, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    validates :phone_number, format: { with: /\A\d+\z/ }, length: { maximum: 15 }
  end
  belongs_to :user_classification
  has_many :products, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_secure_password
end

app/models/user_classification.rb
class UserClassification < ApplicationRecord
  has_many :users, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def index
    @orders = Order.page(params[:page]).per(15).order("created_at DESC")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find_by(id: params[:id])
  end

  def index
    @products = Product.search(params[:search], params[:category_id]).page(params[:page]).per(15).order("created_at DESC")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      log_in user
      redirect_to current_user
    else
      render "/login"
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

  def new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def guest_login
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.alphanumeric(6)
      user.last_name = "太郎"
      user.first_name = "ゲスト"
      user.zipcode = "9999999"
      user.prefecture = "UAE県"
      user.municipality = "ドバイ市"
      user.address = "コンラッド町"
      user.apartments = "エミレーツ"
      user.phone_number = "99999999999"
      user.user_classification_id = 1
      user.delete_flag = false
    end
    log_in(user)
    flash[:notice] = "ゲストユーザーは更新・退会はできません。"
    redirect_to current_user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :show]
  before_action :correct_user,   only: [:edit, :show]
  before_action :ensure_normal_user, only: %i[update destroy]

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.user_classification_id = 1

    if @user.save
      flash[:success] = "ユーザーを登録しました。こちらからログインしてください。"
      redirect_to login_path
    else
      flash[:error] = "登録失敗しました。"
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報の更新終了しました。"
      redirect_to @user
    else
      flash[:error] = "ユーザー情報を更新できませんでした。"
      render :edit
    end
  end

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end

  private
    def user_params
      params.require(:user).permit(
        :first_name,
        :last_name,
        :zipcode,
        :prefecture,
        :municipality,
        :address,
        :apartments,
        :email,
        :phone_number,
        :password,
        :password_confirmation
      )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  private
    def logged_in_user
      unless logged_in?
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end

    def correct_user
      user = User.find(params[:id])
      unless current_user?(user)
        redirect_to root_path
        flash[:danger] = "他人の情報にアクセスすることはできません。。"
      end
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <h1>探求学園Rails専攻</h1>
  <p>© 2020 QuestAcademia, All rights reserved</p>
</footer>

app/views/layouts/_head.html.erb
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <title>探求学園Rails共同開発</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
</head>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
      <div class="navbar-nav me-auto">
        <h1><a class="nav-link navbar-brand" href="#">探求学園Rails専攻</a></h1>
      </div>
      <div>
        <% if logged_in? %>
          <ul>
            <%= current_user.first_name %>　<%= current_user.last_name %><%= 'さん' %>
          </ul>
          <ul class="navbar-nav">
            <%= link_to "商品検索", products_path, class: "nav-link text-dark" %>
            <a class="nav-link text-dark" href="#">カート</a>
            <a class="nav-link text-dark" href="#">注文履歴</a>
            <%= link_to "ユーザ情報", user_path(current_user),class: "nav-link text-dark" %>
            <%= link_to "ログアウト",logout_path, method: :delete, class: "nav-link text-dark" %>
          </ul>
        <% else %>
          <ul>
            <li>
              <%= link_to "ログイン", login_path, class: "text-dark" %>
              <%= link_to "新規登録", new_user_path, class: "text-dark" %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_headre.html.erb
<head>
  <%= link_to 'ゲストログイン（閲覧用）', guest_login_path, method: :post %>
</head>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render'layouts/head'%>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/orders/index.html.erb
<main>
  <div class="container my-4 mt-5">
    <a href="#" class="btn btn-secondary py-0">直近3ヶ月の注文を表示</a>
  </div>
  <% if @orders.present? %>
    <div class="container">
      <hr style="width:90%; opacity:0.9;">
      <table class="table">
        <thead class="table h4">

          <tr>
            <th class="text-start" width="5%">
              No
            </th>
            <th class="text-start" width="20%">
              注文番号
            </th>
            <th class="text-start" width="40%">
              お届け先
            </th>
            <th class="text-start" width="25%">
              備考
            </th>
            <th class="text-start border-0" width="20%"></th>
          </tr>

        </thead>
        <tbody class="h6 font-weight-normal">
  　　　　　<% @orders.each.with_index(1) do |order,index| %>
            <tr>
              <th class="font-weight-normal" scope="row"><%= index %></th>
              <td class="text-left"><%= order.order_number %></td>
              <td class="text-left">
                〒<%= current_user.zipcode %><br />
                <%= current_user.prefecture %><%= current_user.municipality %><%= current_user.address %><%= current_user.apartments %><br />
                <%= current_user.last_name %> <%= current_user.first_name %>様
              </td>
              <td class="text-left">
                注文日時：<%= order.order_date.strftime("%Y/%m/%d") %><br />
                注文状態：<%= order.order_status %>
              </td>
              <td class="border-0 align-middle">
                <%= link_to "詳細", order_path(order) , class:"btn btn-primary btn-sm" %>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
    <div class="container">
      <nav aria-label="...">
        <ul class="pagination justify-content-center">
          <%= paginate @orders %>
        </ul>
      </nav>
    </div>

  <% else %>
    <div class="blockquote mt-5 text-center">
      <h1 style="font-weight: bolder">注文履歴が存在しません</h1>
    </div>
  <% end %>
</main>

app/views/orders/show.html.erb
<main>
  <% if @order.present? %>
    <div class="mt-5 container">
      <div class="jumbotron bg-white">
        <div class="card border-dark">
          <div class="cord-body ml-3">
            <h4 class="mt-4">お届け先</h4>
            <p class="ml-3">〒 <%= @order.user.zipcode %> <%= @order.user.prefecture %><%= @order.user.municipality %><%= @order.user.address %>　</p>
            <p class="offset-sm-2"><%= @order.user.first_name%><%= @order.user.last_name%></p>
          </div>
        </div>
        <div class="mt-5 ml-3">
          <p>注文番号：<%= @order.order_number %></p>
          <p>注文状態：<%= @order.order_status %></p>
        </div>
        <div class="text-end">
          <% if @order.order_status == "準備中" %>
            <button type="button" class="btn btn-danger">注文をキャンセルする</button>
          <% end %>
        </div>
        <table class="table table-borderless mt-3">
          <thead>
            <tr>
              <th scope="col" class="border-top border-bottom">No</th>
              <th scope="col" class="border-top border-bottom">商品名</th>
              <th scope="col" class="border-top border-bottom">商品カテゴリ</th>
              <th scope="col" class="border-top border-bottom">値段</th>
              <th scope="col" class="border-top border-bottom">個数</th>
              <th scope="col" class="border-top border-bottom">小計</th>
              <th scope="col" class="border-top border-bottom">備考</th>
            </tr>
          </thead>
          <tbody>
            <% @order.order_details.each.with_index(1) do |order_detail,index|%>
              <tr>
                <th scope="row"><%= index %></th>
                <td><%= order_detail.product.product_name %></td>
                <td><%= order_detail.product.category.category_name %></td>
                <td><%= order_detail.product.price %></td>
                <td><%= order_detail.order_quantity %>個</td>
                <td><%= order_detail.sub_tatal %>円</td>
                <td><%= order_detail.shipment_status.shipment_status_name %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="border-top border-dark">
          <div class="mt-2 offset-sm-6">
            <p class="ml-4">合計<%= @order.total_price %>円</p>
          </div>
        </div>
        <div class="text-end mb-5">
          <button type="button" class="btn btn-info">注文履歴に戻る</button>
        </div>
      </div>
    </div>
  <% else %>
    <div class="container">
      <div class="jumbotron text-center bg-white"></div>
      <div class="mt-5 text-center">
        <h1>該当注文は見つかりませんでした…</h1>
        <p class="mt-5">注文履歴画面に戻り、やり直してください</p>
        <button type="button" class="btn btn-primary">注文履歴へ</button>
      </div>
    </div>
    </div>
  <% end %>
</main>

app/views/products/index.html.erb
<main>
  <%= form_with url: products_path, method: :get, local: true do |form| %>
    <div class="container mt-5">
        <div class="mx-auto row">
          <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">商品名</label>
          <div class="col-sm-6">
            <%= form.text_field :search, value: @search, class: 'form-control form-control-lg' %>
          </div>
          <div class="col-sm-4 mt-1">
            <%= form.submit '検索', class: 'btn btn-primary', style:"width: 80px;" %>
          </div>
        </div>
    </div>

    <div class="container">
      <div class="mx-auto row">
        <label class="col-sm-2 col-form-label col-form-label-lg" for="exampleFormControlSelect2">商品カテゴリ</label>
        <div class="col-sm-4">
          <%= form.select :category_id, Category.all.map { |category| [ category.category_name, category.id ] },
                                      { include_blank: '未選択', selected: params[:category_id] },
                                      { class: 'form-control', id: 'exampleFormControlSelect2' } %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="container">
    <p>全<%= Product.count %>件</p>
    <table class="table table-hover" border="1" style="border-collapse: collapse">
      <thead>
        <tr class=" table-header">
          <th class="text-left" width="55%">
            商品名
          </th>
          <th class="text-center" width="15%">
            商品カテゴリ
          </th>
          <th class="text-center" width="15%">
            価格
          </th>
          <th class="text-center" width="15%"></th>
        </tr>
      </thead>
      <tbody>
        <% if @products.present? %>
          <% @products.each do |product| %>
            <tr>
              <td scope="row">
                <%= product.product_name %>
              </td>
              <td class="text-center">
                <%= product.category.category_name %>
              </td>
              <td class="text-center">
                <%= product.price %>円
              </td>
              <td class="text-center">
                <%= link_to "商品詳細", product_path(product), class: "btn btn-primary btn-sm" %>
              </td>
            </tr>
          <% end %>

        <% else %>
          <h2 class="text-center">検索結果がありませんでした</h2>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="pagination justify-content-center">
    <%= paginate @products %>
  </div>
</main>

app/views/products/show.html.erb
<main>
  <div class="container">
    <div class="mt-5 jumbotron bg-white">
      <% if @product.present? %>
        <h1 class="text-center">商品情報</h1>
        <h2 class="text-center"><%= @product.product_name %></h2>
        <div class="offset-sm-3">
          <p class="offset-sm-6">商品カテゴリ：<%= @product.category.category_name %></p>
          <p>商品説明</p>
          <p><%= @product.description %></p>
          <p class="mt-4 mb-5">価格：<%= @product.price %>円</p>
        </div>
        <div class="row justify-content-center">
          <label for="order_quanity" class="mt-1 col-sm-1">購入個数</label>
          <div class="col-sm-1">
            <input required type="text" class="form-control" id="order_quanity" pattern="[1-9][0-9]*" min="1">
          </div>
          <label class="mt-1 col-sm-1">個</label>
          <div class="col-sm-2">
            <button type="button" class="btn btn-primary btn-block">カートへ</button>
          </div>
        </div>
      <% else %>
        <div class="mt-5 text-center">
          <h1>該当商品が見つかりませんでした…</h1>
          <p class="mt-5">商品検索画面に戻り、やり直してください</p>
          <%= link_to "商品検索画面へ", products_path, class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/static_pages/home.html.erb
<main>
  <h1 class="mt-5 text-center">探求学園Rails専攻 ECサイト</h1>
  <% if logged_in? %>
    <div class="text-center mt-4">
      <p>ご利用いただき、ありがとうございます<br>
        右上のメニューから商品を検索したり、注文したりできます</p>
    </div>
  <% else %>
    <div class="row d-flex justify-content-center align-items-center">
      <div class="mt-3 mr-3 text-center col-sm-3">
        <p>
          まだアカウントを<br>
          お持ちでない方はこちら
        </p>
        <%= link_to "新規登録", new_user_path, class: "btn btn-primary" %>
    </div>
    <div class="mt-3 ml-3 text-center col-sm-3">
      <p>
        すでにアカウントを<br>
        お持ちの方はこちら
      </p>
      <%= link_to "ログイン", login_path, class: "btn btn-primary" %>
    </div>
  <% end %>
</main>

app/views/static_pages/home_after_login.erb
<main>
  <h1 class="mt-5 text-center">探求学園Rails専攻 ECサイト</h1>
  <div class="text-center mt-4">
    <p>ご利用いただき、ありがとうございます<br>
      右上のメニューから商品を検索したり、注文したりできます</p>
  </div>
</main>

app/views/user/show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html lang="ja">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <title>ユーザー詳細</title>
  <style>
    * {
      margin: 0;
      padding: 0;
    }

    body {
      display: flex;
      /*フッターをウィンドウの最下部に常に表示させるために */
      flex-flow: column;
      /*flexboxのみだと横並びに。これで縦並び */
      position: relative;
      /*←相対位置*/

      padding-bottom: 70px;
      /*←footerの高さ*/
      box-sizing: border-box;
      /*←全て含めてmin-height:100vhにbody全体の表示領域を確保・指定*/
      min-height: 100vh;
      font-family: "Hiragino Kaku Gothic Pro", "ヒラギノ角ゴ Pro W3", メイリオ,
        Meiryo, "ＭＳ Ｐゴシック", "Helvetica
Neue", Helvetica,
sans-serif;
    }

    header {
      background-color: #ffe040;
      z-index: 10;
      /* 要素の重なり順序指定 */
    }

    header h1 {
      font-weight: bold;
    }

    header a {
      font-weight: bold;
      padding-left: 8px;
    }

    header p {
      text-align: right;
    }

    header li {
      list-style: none;
    }

    main {
      background: #ffffff;
      flex: 1;
      /* header footerの高さを除いた、残りの部分がmainで埋まる */
    }

    footer {
      width: 100%;
      background-color: #ffe040;
      position: absolute;
      bottom: 0;
    }

    footer h1 {
      font-size: 15px;
      font-weight: bold;
      margin: 8px 5px;
    }

    footer p {
      text-align: right;
      font-weight: lighter;
      margin: 0 auto;
    }

    .table td {
      border: none;
    }
  </style>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container-fluid">
        <div class="navbar-nav mr-auto">
          <h1><a class="nav-link navbar-brand" href="#">探求学園Rails専攻</a></h1>
        </div>
        <div>
          <ul>
            <p>〇〇 ××さん</p>
          </ul>
          <ul class="navbar-nav">
            <a class="nav-link text-dark" href="#">商品検索</a>
            <a class="nav-link text-dark" href="#">カート</a>
            <a class="nav-link text-dark" href="#">注文履歴</a>
            <a class="nav-link text-dark" href="#">ユーザ情報</a>
            <a class="nav-link text-dark" href="#">ログアウト</a>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <main>

    <section class="text-center pt-5 pb-2">
      <h2 class="mb-4">ユーザ情報</h2>
      <div class="container-fluid">
        <table class="table">
          <tbody>
            <tr>
              <td class="text-center">
                ユーザID
              </td>
              <td>
                User
              </td>
            </tr>

            <tr>
              <td class="text-center">
                氏名
              </td>
              <td>
                ○○ ☓☓
              </td>
            </tr>

            <tr>
              <td class="text-center">
                住所
              </td>
              <td>
                〒○〇〇-○○○○<br>
                沖縄県那覇市○○ ○-○-◯
              </td>
            </tr>
            <tr>
              <td class="text-center">
                電話番号
              </td>
              <td>
                ○○○-○○○○-○〇〇○
              </td>
            <tr>
              <td class="text-center">
                メールアドレス
              </td>
              <td>
                User@example.com
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>

    <div class="text-center">
      <a class="btn btn-primary" href="#" role="button">修正/退会する</a>
    </div>

  </main>
  <footer>
    <h1>探求学園Rails専攻</h1>
    <p>© 2020 QuestAcademia, All rights reserved</p>
  </footer>

</body>

</html>

app/views/users/edit.html.erb
<main>
  <h2 class="text-center mt-5">ユーザ情報修正</h2>
  <%= form_with model: @user, local: true do |form|%>
    <%= render 'layouts/error_messages', model: form.object %>
    <%= flash[:success] %>
    <%= flash[:error] %>
    <table width="50%" style="margin-left:350px">
      <tr height="40">
        <td align="center">
          氏名
        </td>
        <td>
          <%= form.label :first_name, "姓" %>
          <%= form.text_field :first_name %>
          <%= form.label :last_name, "名" %>
          <%= form.text_field :last_name %>
        </td>
      </tr>

      <tr height="40">
        <td align="center">
          住所
        </td>
        <td colspan="2">
          <%= form.label :zipcode, "〒" %>
          <%= form.text_field :zipcode %>
        </td>
      </tr>

      <tr height="40">
        <td colspan="2">
          <%= form.label :prefecture, "都道府県" %>
          <%= form.text_field :prefecture %>
        </td>
      </tr>

      <tr height="40">
        <td>
          <%= form.label :municipality, "市町村区" %>
          <%= form.text_field :municipality %>
        </td>
      </tr>

      <tr height="40">
        <td>
          <%= form.label :address, "番地" %>
          <%= form.text_field :address %>
        </td>
      </tr>

      <tr height="40">
        <td>
          <%= form.label :apartments, "マンション　部屋番号" %>
          <%= form.text_field :apartments %>
        </td>
      </tr>

      <tr height="40">
        <td>
          <%= form.label :email, "メールアドレス" %>
          <%= form.text_field :email %>
        </td>
      </tr>

      <tr height="40">
        <td>
          <%= form.label :phone_number, "電話番号" %>
          <%= form.text_field :phone_number %>
        </td>
      </tr>

      <tr height="40">
        <td>
          <%= form.label :password, "パスワード" %>
          <%= form.password_field :password %>
        </td>
      </tr>

      <tr height="40">
        <td>
          <%= form.label :password_confirmation, "パスワード（再入力）" %>
          <%= form.password_field :password_confirmation %>
        </td>
      </tr>
    </table>

    <div class="row mt-5">
      <div class="col-5">
        <div class="d-flex justify-content-end">
          <%= form.submit "修正", class: "btn btn-primary" %>
        </div>
      </div>

      <div class="col-5 offset-2">
        <button class="btn btn-danger" type="submit">退会</button>
      </div>
    </div>
  <% end %>
</main>

app/views/users/new.html.erb
<main>
  <div class="container">
  <%= form_with model: @user do |form|%>
    <div class="jumbotron text-center bg-white mt-5">
      <h2>お客様情報登録</h2>
      <%= flash[:error] %>
    </div>
    <div class="row mb-5 ml-5">
      <div class="col-sm-6 offset-sm-3">
        <div>
          <p>氏名</p>
          <div class="row ms-2">
            <div class="col-sm-5">
              <%= form.label :last_name, "姓" %>
              <%= form.text_field :last_name, maxlength: 10 %>
              <%= form.label :first_name, "名" %>
              <%= form.text_field :first_name,maxlength: 10 %>
            </div>
          </div>
          <%= form.label :zipcode, "郵便番号" %>
          <div class="col-sm-6 ms-4">
            <%= form.text_field :zipcode, length: 8 %>
          </div>
          <div>
            <p class="mb-1">住所</p>
            <div class="ms-4">
              <div class="row">
                <%= form.label :prefecture, "都道府県" %>
                <%= form.text_field :prefecture, maxlength: 5 %>
              </div>
              <div class="row">
                <%= form.label :municipality, "市町村区" %>
                <%= form.text_field :municipality, maxlength: 10 %>
              </div>
              <div class="row">
                  <%= form.label :address, "番地" %>
                  <%= form.text_field :address, maxlength: 15 %>
              </div>
              <div class="row">
                  <%= form.label :apartments, "マンション　部屋番号" %>
                  <%= form.text_field :apartments, maxlength: 20 %>
              </div>
            </div>
          </div>
        </div>
        <div>
          <%= form.label :email, "メールアドレス" %>
          <div class="ml-3 mr-5 ms-4">
            <%= form.text_field :email %>
          </div>
        </div>
        <div>
          <%= form.label :phone_number, "電話番号" %>
          <div class="ml-3 mr-5 ms-4">
            <%= form.text_field :phone_number %>
          </div>
        </div>
        <div>
          <%= form.label :password, "パスワード" %>
          <div class="col-sm-8 ms-4">
            <%= form.password_field :password %>
          </div>
        </div>
        <div>
          <%= form.label :zipcode, "パスワード再入力" %>
          <div class="col-sm-8 ms-4">
            <%= form.password_field :password_confirmation %>
          </div>
        </div>
        <div class="row justify-content-center">
          <div class="col-sm-2 mt-5">
            <%= form.submit "登録", class: "btn btn-primary" %>
          </div>
        </div>
        <div class="mt-5 text-center">
          <%= link_to "ログインはこちらから", login_path %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
 </main>